### PR TITLE
fix(hooks): pass response correctly, pass input arg when available

### LINKED ISSUE #26: mutatingPostResolveHook not returning data.
### Bug description

Hi, I am trying to use the mutatingPostResolve hook and the go process is not returning the value returned from the post resolve hook.
Without the post resolve hook, everything works perfectly.

The request is traveling to the resolving API, back, then to the mutating hook, then the correct value is coming back, but then no data is returned to the initiating client. The body is entirely empty.

Here is the info from the stdout:

```
--- ClientRequest start ---

GET /api/main/operations/coreGIGet?id=0 HTTP/1.1
Host: localhost:9991
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
Connection: keep-alive
Cookie: token=14402056-ebb1-466e-b968-3fee014eb778
Dnt: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: cross-site
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0





--- ClientRequest end ---



--- DebugTransport ---

Request:

POST / HTTP/1.1
Host: localhost:8000
Accept: application/json
Content-Type: application/json

{"variables":{"id":0},"query":"query($id: Int!){objects: sObjects(ids: [$id]){description image labels}}"}

Duration: 117 ms

Response:

HTTP/1.1 200 OK
Content-Length: 70
Content-Type: application/json
Date: Fri, 03 Jun 2022 04:00:07 GMT
Server: uvicorn

{"data":{"objects":[{"description":null,"image":null,"labels":null}]}}

--- DebugTransport

2022/06/03 14:00:08 [DEBUG] POST http://127.0.0.1:9992/operation/coreGIGet/mutatingPostResolve
{"level":30,"time":1654228808432,"pid":316252,"hostname":"my-host","reqId":"req-1","req":{"method":"POST","url":"/operation/coreGIGet/mutatingPostResolve","hostname":"127.0.0.1:9992","remoteAddress":"127.0.0.1","remotePort":41122},"msg":"incoming request"}
received data: {"data":{"objects":[{"description":null,"image":null,"labels":null}]}}
{"level":30,"time":1654228808448,"pid":316252,"hostname":"my-host","reqId":"req-1","res":{"statusCode":200},"responseTime":13.967247009277344,"msg":"request completed"}
```

Below are the captures from wireshark for the mutating post resolve side:

Here is the request to the mutating post resolver:
```
EL*@@í7 ¢'ÜW´Uí
@Æí@ÆìPOST /operation/coreGIGet/mutatingPostResolve HTTP/1.1
Host: 127.0.0.1:9992
User-Agent: Go-http-client/1.1
Content-Length: 673
Content-Type: application/json
Accept-Encoding: gzip

{"__wg":{"client_request":{"method":"GET","requestURI":"/api/main/operations/coreGIGet?id=0","headers":{"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8","Accept-Encoding":"gzip, deflate, br","Accept-Language":"en-US,en;q=0.5","Connection":"keep-alive","Cookie":"token=14402056-ebb1-466e-b968-3fee014eb778","Dnt":"1","Sec-Fetch-Dest":"document","Sec-Fetch-Mode":"navigate","Sec-Fetch-Site":"cross-site","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"}}},"input":{"id":0},"response":{"data":{"objects":[{"description":null,"image":null,"labels":null}]}}}
```
And here is the response:
```
E}Ã@@x_' ¢´UíÜ"·ÿq
@Ç@ÆíHTTP/1.1 200 OK
content-type: application/json; charset=utf-8
content-length: 158
Date: Fri, 03 Jun 2022 04:00:08 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"op":"coreGIGet","hook":"mutatingPostResolve","input":{"data":{"objects":[{"description":null,"image":null,"labels":null}]}},"setClientRequestHeaders":{}}
```

Here is the HAR extract from the final response to the browser:
```
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Content-Type",
              "value": "application/json"
            },
            {
              "name": "ETag",
              "value": "W/\"17241709254077376921\""
            },
            {
              "name": "Vary",
              "value": "Origin"
            },
            {
              "name": "Date",
              "value": "Fri, 03 Jun 2022 04:33:00 GMT"
            },
            {
              "name": "Content-Length",
              "value": "0"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "application/json",
            "size": 0,
            "text": ""
          },
          "redirectURL": "",
          "headersSize": 153,
          "bodySize": 153
        }
```
From looking at the above information, If I was to guess why this is failing, I would say it's because the mutatingPostResolve hook is populating the "input" field with the response data on the response from the mutatingpostresolve hook (the wireshark capture)

### How to reproduce

Create a mutatingPostResolveHook and see if it returns the correct data

### Expected behavior

The correct data is returned from the hook.

### WunderGraph information

here is the hook definition:
It just returns the unmodified data (I removed all mutations when I had issues)
```
        queries: {
            coreGIGet: {
                async mutatingPostResolve(ctx: Context, input: coreGIGetInput, response) {
                    console.log(`received data: ${JSON.stringify(response)}`)
                    return response
                },
            },
        },

``` 

### Environment & setup

node:  v14.17.6
@wundergraph/sdk: 0.90.6
linux

### WunderCtl Version

```
0.90.25
```

### PR DESCRIPTION
**Pull request by StarpTech**
Fix #26 

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

File: pkg/apihandler/apihandler.go [hunk 1]
```diff
@@ -1980,6 +1980,7 @@ func hookBaseData(r *http.Request, buf []byte, variables []byte, response []byte
 	if clientRequestData, err := HttpRequestToWunderGraphRequestJSON(r, false); err == nil {
 		buf, _ = jsonparser.Set(buf, clientRequestData, "__wg", "client_request")
 	}
+	// TODO don't pass empty object '{}' when no variables are passed
```
Comment (jensneuse) [inline pkg/apihandler/apihandler.go:1983]: Keep in mind that empty variables are always '{}', otherwise the validation will fall.

**Review by jensneuse — APPROVED** [review]

File: pkg/apihandler/apihandler.go (hunk 1 above)
Comment (StarpTech) [reply pkg/apihandler/apihandler.go:1983]: Good point.
